<a href="https://colab.research.google.com/github/NeshPk/NeshPk/blob/main/M_Products.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### 【Problem 1 】 Hand calculate matrix

Row 1 of A, Column 1 of B
(-1 * 0) + (2 * 0) + (3 * 2) = 0 + 0 + 6 = 6

Row 1 of A, Column 2 of B:
(-1 * 2) + (2 * 2) + (3 * 9) = -2 + 4 + 27 = 29

Row 1 of A, Column 3 of B:
(-1 * 1) + (2 * -8) + (3 * -1) = -1 - 16 - 3 = -20

Row 2 of A, Column 1 of B:
(4 * 0) + (-5 * 0) + (6 * 2) = 0 + 0 + 12 = 12

Row 2 of A, Column 2 of B:
(4 * 2) + (-5 * 2) + (6 * 9) = 8 - 10 + 54 = 52

Row 2 of A, Column 3 of B:
(4 * 1) + (-5 * -8) + (6 * -1) = 4 + 40 - 6 = 38

Row 3 of A, Column 1 of B:
(7 * 0) + (8 * 0) + (-9 * 2) = 0 + 0 - 18 = -18

Row 3 of A, Column 2 of B:
(7 * 2) + (8 * 2) + (-9 * 9) = 14 + 16 - 81 = -51

Row 3 of A, Column 3 of B:
(7 * 1) + (8 * -8) + (-9 * -1) = 7 - 64 + 9 = -48

##### 【Problem 2 】 Calculation by a function of NumPy

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 1. Using np.matmul():
result_matmul = np.matmul(a_ndarray, b_ndarray)
print("Result using np.matmul():\n", result_matmul)

# 2. Using np.dot():
result_dot = np.dot(a_ndarray, b_ndarray)
print("\nResult using np.dot():\n", result_dot)

# 3. Using @ operator:
result_at = a_ndarray @ b_ndarray
print("\nResult using @ operator:\n", result_at)


Result using np.matmul():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using np.dot():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using @ operator:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##### 【Problem 3 】 Implement calculation of certain elements

In [2]:
def calculate_element_00(matrix_a, matrix_b):

    result = 0
    for k in range(matrix_a.shape[1]):  # Iterate through columns of A (or rows of B)
        result += matrix_a[0, k] * matrix_b[k, 0]
    return result

element_00 = calculate_element_00(a_ndarray, b_ndarray)
print("Element (0, 0) of the matrix product:", element_00)

Element (0, 0) of the matrix product: 6


##### Problem 4 】 Creating a function to perform matrix products

In [ ]:
def matrix_multiply_scratch(matrix_a, matrix_b):

    rows_a = matrix_a.shape[0]
    cols_a = matrix_a.shape[1]
    cols_b = matrix_b.shape[1]

    # Initialize the result matrix with zeros
    result_matrix = np.zeros((rows_a, cols_b))

    for i in range(rows_a):  # Iterate through rows of A
        for j in range(cols_b):  # Iterate through columns of B
            for k in range(cols_a):  # Iterate through columns of A (or rows of B)
                result_matrix[i, j] += matrix_a[i, k] * matrix_b[k, j]

    return result_matrix

result = matrix_multiply_scratch(a_ndarray, b_ndarray)
print("Matrix product from scratch:\n", result)

Matrix product from scratch:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


##### 【Problem 5 】 Determine input whose calculation is not defined

In [ ]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def matrix_multiply_scratch(matrix_a, matrix_b):

    rows_a = matrix_a.shape[0]
    cols_a = matrix_a.shape[1]
    rows_b = matrix_b.shape[0]
    cols_b = matrix_b.shape[1]

    # Check if the matrices can be multiplied
    if cols_a != rows_b:
        print("Error: Matrices cannot be multiplied. Number of columns in the first matrix must equal the number of rows in the second matrix.")
        print(f"Matrix A shape: {matrix_a.shape}")
        print(f"Matrix B shape: {matrix_b.shape}")
        return None  # Return None to indicate an error

    # Initialize the result matrix with zeros
    result_matrix = np.zeros((rows_a, cols_b))

    for i in range(rows_a):  # Iterate through rows of A
        for j in range(cols_b):  # Iterate through columns of B
            for k in range(cols_a):  # Iterate through columns of A (or rows of B)
                result_matrix[i, j] += matrix_a[i, k] * matrix_b[k, j]

    return result_matrix

result_de = matrix_multiply_scratch(d_ndarray, e_ndarray)
print("Matrix product D * E:\n", result_de)

Error: Matrices cannot be multiplied. Number of columns in the first matrix must equal the number of rows in the second matrix.
Matrix A shape: (2, 3)
Matrix B shape: (2, 3)
Matrix product D * E:
 None


##### 【Problem 6 】 Transposition

In [ ]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

#Using np.transpose()
e_transposed_transpose = np.transpose(e_ndarray)
print("E Transposed using np.transpose():\n", e_transposed_transpose)

#Using .T attribute:
e_transposed_t = e_ndarray.T
print("E Transposed using .T:\n", e_transposed_t)

#calvulate the matrix product
result_d_etranspose = np.matmul(d_ndarray, e_transposed_t)
print("Matrix product D * E.T:\n", result_d_etranspose)



E Transposed using np.transpose():
 [[-9  6]
 [ 8 -5]
 [ 7  4]]
E Transposed using .T:
 [[-9  6]
 [ 8 -5]
 [ 7  4]]
Matrix product D * E.T:
 [[ 46  -4]
 [-34  73]]
